BEGIN;

-- Reset des templates Envato puis re-insertion propre (url live + vignette).
DELETE FROM public.design_references WHERE kind='template';

INSERT INTO public.design_references (name, kind, url, repo_url, preview_url, sector, tags, notes) VALUES
 ('bizzar v1.0','template','/galerie/inspiration-1/bizzar%20v1.0/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-1','/inspiration/inspiration-1.png','business / corporate / consulting',ARRAY['corporate','consulting','services','shop','blog'],'Template inspiration-1. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Playhost - Game Hosting Website Template','template','/galerie/inspiration-2/Playhost%20HTML/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-2','/inspiration/inspiration-2.png','hosting / game-server / SaaS tech',ARRAY['hosting','web-hosting','game-server','datacenter','pricing'],'Template inspiration-2. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Nictorys - Factory & Industrial HTML Template','template','https://spaceraceit.com/html/nictorys/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-3','/inspiration/nictorys.png','industriel / factory / B2B corporate',ARRAY['industrie','factory','btp','oil-gas','logistique'],'Template inspiration-3. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Ahope - Responsive HTML Hosting Template','template','/galerie/inspiration-4/ahope-html/light_version/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-4','/inspiration/ahope.png','hosting / domaine / WHMCS / SaaS',ARRAY['hosting','domaine','whmcs','vps','wordpress'],'Template inspiration-4. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Slake - Web Hosting, Domain and WHMCS HTML Template','template','https://marveltheme.com/tf/html/slake/slake/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-5','/inspiration/slake.png','hosting / domaine / WHMCS / isométrique',ARRAY['hosting','domaine','whmcs','vps','cloud'],'Template inspiration-5. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('MYKD - eSports and Gaming NFT Template','template','/galerie/inspiration-6/mykd/index-4.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-6','/inspiration/esports.png','eSports / gaming / NFT / dark',ARRAY['esports','gaming','nft','tournament','shop'],'Template inspiration-6. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Muzilla - Creative Indie Game Studios NextJS Template','template','https://muzilla-nextjs.vercel.app/','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-7','/inspiration/muzilla.png','indie game studio / eSports',ARRAY['nextjs','react','typescript','gaming','indie-game'],'Template inspiration-7. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Sepia - Photography Portfolio HTML Website Template','template','https://demo.themetorium.net/html/sepia/','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-8','/inspiration/sepia.png','photographie / portfolio / creatif',ARRAY['photographie','portfolio','galerie','creatif','blog'],'Template inspiration-8. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Elexer - Photography Portfolio Template','template','/galerie/inspiration-9/html/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-9','/inspiration/elexer.jpg','photographie / portfolio minimal / dark',ARRAY['photographie','portfolio','galerie','minimal','dark'],'Template inspiration-9. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Oblo - Showcase Portfolio & Agency Template','template','/galerie/inspiration-10/template/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-10','/inspiration/oblo.png','portfolio / agence creative / dark editorial',ARRAY['portfolio','agence','creatif','showcase','dark'],'Template inspiration-10. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Okai - Creative Portfolio & Agency HTML Template','template','/galerie/inspiration-11/okai/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-11','/inspiration/okai.jpg','agence creative / portfolio / dark coral',ARRAY['portfolio','agence','creatif','dark','animations'],'Template inspiration-11. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Aster - Portfolio Agency Template','template','/galerie/inspiration-12/template/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-12','/inspiration/aster.png','portfolio / agence creative / gradient editorial',ARRAY['portfolio','agence','creatif','slider','gradient'],'Template inspiration-12. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('MAZE - Photography Portfolio HTML Template','template','/galerie/inspiration-13/HTML/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-13','/inspiration/maze.png','photographie / portfolio / dark & gold',ARRAY['photographie','portfolio','personal','dark','gold'],'Template inspiration-13. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Photogen - Photography HTML Template','template','https://htmldesigntemplates.com/html/photogen/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-14','/inspiration/photogen.png','photographie / multipurpose / dark & gold',ARRAY['photographie','portfolio','galerie','shop','multipurpose'],'Template inspiration-14. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Restfast - Fast Food Restaurant React Template','template','https://restfast-react.vercel.app/','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-15','/inspiration/restfast.png','restauration / fast-food / food',ARRAY['react','vite','tailwind','restaurant','fast-food'],'Template inspiration-15. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Fresheat - Fast Food & Restaurant ReactJS Template','template','https://fresheat-react.vercel.app/','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-16','/inspiration/fresheat.png','fast-food / restaurant / chicken-burger',ARRAY['react','vite','restaurant','fast-food','food'],'Template inspiration-16. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Foodix - Fast Foods & Restaurants NextJS Template','template','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-17','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-17','/inspiration/foodix.png','fast-food / restaurant / burger-pizza-sushi',ARRAY['nextjs','react','swiper','restaurant','fast-food'],'Template inspiration-17. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('WellFood - Fast Food & Restaurant HTML Template','template','/galerie/inspiration-18/HTML%20Template/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-18','/inspiration/wellfood.jpg','fast-food / restaurant multi-cuisine',ARRAY['restaurant','fast-food','food','menu','burger'],'Template inspiration-18. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Kaffen - Cafe & Restaurant HTML Template','template','https://bslthemes.com/html/kaffen/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-19','/inspiration/kaffen.png','cafe / coffee shop / restaurant dark premium',ARRAY['cafe','coffee','restaurant','reservation','food'],'Template inspiration-19. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Bistly - Restaurant & Cafe HTML Template','template','/galerie/inspiration-20/bistly/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-20','/inspiration/bistly.jpg','restaurant & cafe elegant / fine-dining / patisserie',ARRAY['restaurant','cafe','bakery','gsap','reservation'],'Template inspiration-20. Apercu galerie GND. Convertir vers stack GND avant usage client.'),
 ('Cafe360 - Restaurant & Cafe OnePage','template','/galerie/inspiration-21/Cafe360-Restaurant-OnePage-HTML/index.html','https://github.com/gnd63consulting-hue/gnd-template-library/tree/main/inspiration-21','/inspiration/inspiration-21.png','restaurant / café / one-page',ARRAY['restaurant','cafe','coffee','food','onepage'],'Template inspiration-21. Apercu galerie GND. Convertir vers stack GND avant usage client.');

NOTIFY pgrst, 'reload schema';
COMMIT;

SELECT count(*) AS templates FROM public.design_references WHERE kind='template';